'use client';
import { Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Search } from 'lucide-react';
import { api, type Booking } from '@/lib/api';
import { useToast } from '@/providers/ToastProvider';
import AdminPageHeader from '@/components/dashboard/AdminPageHeader';
import { AdminEmpty, AdminError, AdminLoading } from '@/components/dashboard/AdminState';

const labels: Record<string, string> = { PENDING: 'Chờ xác nhận', CONFIRMED: 'Đã xác nhận', RENTING: 'Đang thuê', COMPLETED: 'Hoàn tất', CANCELLED: 'Đã hủy' };
const nextActions: Record<string, Array<{ status: string; label: string }>> = { PENDING: [{ status: 'CONFIRMED', label: 'Xác nhận' }, { status: 'CANCELLED', label: 'Từ chối' }], CONFIRMED: [{ status: 'RENTING', label: 'Giao xe' }, { status: 'CANCELLED', label: 'Hủy đơn' }], RENTING: [{ status: 'COMPLETED', label: 'Nhận xe trả' }] };

function AdminBookingsContent() {
  const searchParams = useSearchParams();
  const toast = useToast(); const [items, setItems] = useState<Booking[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState(searchParams.get('status') || 'ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await api.bookings.findAll()); } catch (err) { setError(err instanceof Error ? err.message : 'Không thể tải đơn thuê.'); } finally { setLoading(false); } }, []); useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => items.filter((item) => `${item.bookingNumber} ${item.customer?.fullName || ''} ${item.vehicle?.plateNumber || ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'ALL' || item.status === status)), [items, query, status]);
  const changeStatus = async (item: Booking, next: { status: string; label: string }) => { if (!window.confirm(`${next.label} đơn ${item.bookingNumber}?`)) return; setBusy(item.id); try { const updated = await api.bookings.updateStatus(item.id, next.status); setItems((current) => current.map((entry) => entry.id === updated.id ? { ...entry, ...updated } : entry)); toast.success(`Đã ${next.label.toLowerCase()} đơn.`); } catch (err) { toast.error(err instanceof Error ? err.message : 'Không thể cập nhật đơn.'); } finally { setBusy(''); } };
  return <div><AdminPageHeader title="Quản lý đơn thuê" description="Theo dõi đơn từ lúc chờ xác nhận đến khi hoàn tất và kiểm soát đúng chuỗi trạng thái." />
    <div className="mb-4 grid gap-3 rounded-2xl border border-app-border/40 bg-app-surface p-4 sm:grid-cols-[1fr_220px]"><label className="relative"><span className="sr-only">Tìm đơn</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-content-secondary" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Mã đơn, khách hàng, biển số" className="min-h-11 w-full rounded-xl border border-app-border pl-10 pr-3 text-sm focus:border-brand focus:outline-none focus:ring-4 focus:ring-brand/20" /></label><select aria-label="Lọc trạng thái đơn" value={status} onChange={(e) => setStatus(e.target.value)} className="min-h-11 rounded-xl border border-app-border px-3"><option value="ALL">Tất cả trạng thái</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    {loading ? <AdminLoading /> : error ? <AdminError message={error} onRetry={() => void load()} /> : filtered.length === 0 ? <AdminEmpty message="Không có đơn thuê phù hợp." /> : <div className="overflow-x-auto rounded-2xl border border-app-border/40 bg-app-surface"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-app-muted text-xs uppercase text-content-secondary"><tr><th className="p-4">Mã đơn</th><th className="p-4">Khách hàng</th><th className="p-4">Xe</th><th className="p-4">Thời gian</th><th className="p-4">Tổng tiền</th><th className="p-4">Trạng thái</th><th className="p-4 text-right">Thao tác</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-app-border/30"><td className="p-4 font-bold">{item.bookingNumber}</td><td className="p-4"><p className="font-semibold">{item.customer?.fullName || '—'}</p><p className="text-xs text-content-secondary">{item.customer?.phone}</p></td><td className="p-4">{item.vehicle ? `${item.vehicle.brand} ${item.vehicle.model} · ${item.vehicle.plateNumber}` : '—'}</td><td className="p-4 text-xs">{item.startDate ? new Date(item.startDate).toLocaleDateString('vi-VN') : '—'} → {item.endDate ? new Date(item.endDate).toLocaleDateString('vi-VN') : '—'}</td><td className="p-4 font-bold">{item.totalPrice.toLocaleString('vi-VN')} đ</td><td className="p-4"><span className="rounded-full bg-app-muted px-2 py-1 text-xs font-bold">{labels[item.status] || item.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><Link href={`/dashboard/bookings/${item.id}`} className="inline-flex min-h-11 items-center rounded-lg px-3 font-bold text-brand hover:bg-utility">Chi tiết</Link>{(nextActions[item.status] || []).map((action) => <button key={action.status} disabled={busy === item.id} onClick={() => void changeStatus(item, action)} className={`min-h-11 rounded-lg px-3 text-xs font-bold disabled:opacity-50 ${action.status === 'CANCELLED' ? 'text-danger hover:bg-danger-muted' : 'bg-brand text-on-brand hover:bg-brand-hover'}`}>{action.label}</button>)}</div></td></tr>)}</tbody></table></div>}
  </div>;
}

export default function AdminBookingsPage() { return <Suspense fallback={<AdminLoading />}><AdminBookingsContent /></Suspense>; }
